"""Pure policy checks for tool calls made inside a workstream session.

Each check returns None (allowed) or a reason string that is shown to Claude.
Bash analysis is best-effort; the PostToolUse drift check catches what slips through.
"""

from __future__ import annotations

import os
import shlex
from dataclasses import dataclass, field
from pathlib import Path

FILE_TOOLS = {"Edit": "file_path", "Write": "file_path", "MultiEdit": "file_path", "NotebookEdit": "notebook_path"}
MANAGER_FILES = ("CLAUDE.md", ".claude/settings.json")
SEPARATORS = {";", "&&", "||", "|", "&", "(", ")", "\n"}


@dataclass
class Context:
    ws_key: str
    folder: Path  # workstream root
    cwd: Path  # Bash working directory at the time of the call
    code_roots: list[Path]
    branches: dict[str, str]  # worktree folder name -> expected branch
    writable: list[Path] = field(default_factory=list)  # also editable: shared memory, session scratchpad


def _within(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
        return True
    except ValueError:
        return False


def _abs(p: str, cwd: Path) -> Path:
    return Path(os.path.normpath(cwd / os.path.expanduser(p)))


def _in_code_roots(path: Path, ctx: Context) -> bool:
    return not _within(path, ctx.folder) and any(_within(path, r) for r in ctx.code_roots)


READ_ONLY_GIT = {"log", "show", "diff", "status", "blame", "grep", "branch", "rev-parse", "ls-files", "remote"}


def redirect(path: Path, ctx: Context) -> str:
    """Tell Claude where to work instead of an original checkout (or how to attach the repo)."""
    for root in ctx.code_roots:
        if _within(path, root) and path != root:
            repo, *rest = path.relative_to(root).parts
            if repo in ctx.branches:
                alt = ctx.folder / repo / Path(*rest) if rest else ctx.folder / repo
                return f"{repo} is attached to this workstream: use {alt} (branch {ctx.branches[repo]}) instead."
            return (
                f"{repo} is not attached to workstream {ctx.ws_key}. If this task needs it, first run "
                f"`wm add-repo {ctx.ws_key} {repo}` (creates the worktree {ctx.folder / repo} and the branch), "
                "then work there."
            )
    return f"Work inside the repo subfolders of {ctx.folder}."


def check_file_tool(tool: str, tool_input: dict, ctx: Context) -> str | None:
    raw = tool_input.get(FILE_TOOLS[tool]) or ""
    if not raw:
        return None
    path = _abs(raw, ctx.cwd)
    if not _within(path, ctx.folder):
        # resolved, so a symlink inside these folders can't lead elsewhere
        if any(_within(path.resolve(), d.resolve()) for d in ctx.writable):
            return None
        return f"Blocked: {path} is outside workstream {ctx.ws_key}. " + redirect(path, ctx)
    rel = path.relative_to(ctx.folder).as_posix()
    if rel in MANAGER_FILES:
        return f"Blocked: {rel} is generated by the workstream manager. Use `wm set` / `wm add-repo` instead."
    return None


def check_agent(tool_input: dict, ctx: Context) -> str | None:
    if tool_input.get("isolation") == "worktree":
        return (
            "Blocked: subagents must not use worktree isolation in a workstream; the worktrees are managed "
            "by `wm`. Launch the subagent without isolation and point it at the right repo subfolder."
        )
    return None


def check_enter_worktree(ctx: Context) -> str:
    return (
        f"Blocked: workstream {ctx.ws_key} already runs in managed worktrees (the repo subfolders). "
        f"Work there; to add a repo run `wm add-repo {ctx.ws_key} <repo>`."
    )


def _segments(command: str) -> list[list[str]]:
    lexer = shlex.shlex(command, posix=True, punctuation_chars=";&|()\n")
    lexer.whitespace_split = True
    lexer.commenters = ""
    segs: list[list[str]] = [[]]
    try:
        for tok in lexer:
            if tok in SEPARATORS or set(tok) <= set(";&|()"):
                segs.append([])
            else:
                segs[-1].append(tok)
    except ValueError:  # unbalanced quotes: fall back to whitespace split
        return [command.split()]
    return [s for s in segs if s]


GIT_OPTS_WITH_VALUE = {"-C", "-c", "--git-dir", "--work-tree", "--namespace"}


def _parse_git(args: list[str]) -> tuple[list[str], list[str]]:
    """Split `git` argv (without 'git') into (-C paths, [subcommand, *rest])."""
    c_paths: list[str] = []
    i = 0
    while i < len(args):
        a = args[i]
        if a in GIT_OPTS_WITH_VALUE and i + 1 < len(args):
            if a == "-C":
                c_paths.append(args[i + 1])
            i += 2
            continue
        if a.startswith("--git-dir=") or a.startswith("--work-tree="):
            c_paths.append(a.split("=", 1)[1])
            i += 1
            continue
        if a.startswith("-"):
            i += 1
            continue
        break
    return c_paths, args[i:]


def _strip_env(seg: list[str]) -> list[str]:
    i = 0
    while i < len(seg) and "=" in seg[i] and not seg[i].startswith("-") and seg[i].split("=")[0].isidentifier():
        i += 1
    if i < len(seg) and seg[i] in ("sudo", "command", "exec", "time", "nohup"):
        i += 1
    return seg[i:]


def check_bash(command: str, ctx: Context) -> str | None:
    cwd = ctx.cwd
    for seg in _segments(command):
        seg = _strip_env(seg)
        if not seg:
            continue
        prog = os.path.basename(seg[0])

        if prog in ("cd", "pushd") and len(seg) > 1:
            target = _abs(seg[1], cwd)
            if _in_code_roots(target, ctx):
                return (
                    f"Blocked: `cd {seg[1]}` enters an original checkout. " + redirect(target, ctx)
                    + " (Reading other paths with cat/grep/git log is fine.)"
                )
            cwd = target
            continue

        if prog != "git":
            continue
        c_paths, rest = _parse_git(seg[1:])
        git_cwd = cwd
        for p in c_paths:
            git_cwd = _abs(p, git_cwd)
        if not rest:
            continue
        sub, sub_args = rest[0], rest[1:]
        if _in_code_roots(git_cwd, ctx) and sub not in READ_ONLY_GIT:
            return f"Blocked: `git {sub}` would run in an original checkout ({git_cwd}). " + redirect(git_cwd, ctx)
        if sub == "clone":
            return (
                f"Blocked: don't clone repos into workstream {ctx.ws_key}. Run `wm add-repo {ctx.ws_key} <repo>` "
                "to attach a repo from ~/code as a managed worktree."
            )

        if sub == "worktree" and (not sub_args or sub_args[0] not in ("list",)):
            return (
                f"Blocked: worktrees are managed by `wm` in workstream {ctx.ws_key}. "
                f"To add a repo run `wm add-repo {ctx.ws_key} <repo>`."
            )
        if sub == "switch" and not set(sub_args) & {"-h", "--help"}:
            return _branch_msg(ctx, git_cwd)
        if sub == "checkout":
            if "--" in sub_args or sub_args in ([], ["."]) or set(sub_args) & {"-p", "--patch"}:
                continue
            return _branch_msg(ctx, git_cwd) + " To restore files use `git restore <path>` or `git checkout -- <path>`."
        if sub == "branch" and set(sub_args) & {"-m", "-M", "--move"}:
            return "Blocked: renaming branches breaks the workstream's branch mapping; keep the branch names."
    return None


def _branch_msg(ctx: Context, git_cwd: Path) -> str:
    folder = next((f for f in ctx.branches if _within(git_cwd, ctx.folder / f)), None)
    expected = f" Stay on {ctx.branches[folder]}." if folder else ""
    return (
        f"Blocked: switching branches is not allowed in workstream worktrees.{expected} "
        "Read other branches with `git show <branch>:<path>` or `git diff <branch>`."
    )
