"""Generated workstream files: CLAUDE.md and .claude/settings.json (both manager-owned)."""

from __future__ import annotations

import json
import shlex
from pathlib import Path

from .db import RepoLink, Workstream

TASK_FILE = "TASK.md"

TASK_FORMAT = """\
---
key: {key}
ticket: {ticket}
name: {name}
---
## Goal
## Context
(what the user said, cleaned up — keep their wording where it matters)
## Done when
- [ ] checkable acceptance criteria
## Out of scope
## Open questions
## Decisions & progress
(append at meaningful milestones: what changed, where, why)"""


def claude_md(ws: Workstream, repos: list[RepoLink], available_repos: list[str], memory_dir: Path,
              pending_repos: list[str] | None = None) -> str:
    key = ws.key
    title = " · ".join(p for p in (key, ws.ticket if ws.ticket != key else None, ws.name) if p)
    has_task = (ws.path / TASK_FILE).exists()
    out: list[str] = [f"# Workstream {title}", ""]
    out += [
        "This folder is the root of a workstream managed by `wm` (agents manager). Each subfolder listed under",
        "Repos is a git worktree dedicated to this workstream. This file is regenerated by `wm`; don't edit it.",
        "",
    ]
    if has_task:
        out += [f"@{TASK_FILE}", ""]
    else:
        pending = ""
        if pending_repos:
            pending = f" The user already selected these repos: {', '.join(pending_repos)}."
        fmt = TASK_FORMAT.format(key=key, ticket=ws.ticket or "", name=ws.name or "<3 words>")
        out += [
            f"## Intake — do this first ({TASK_FILE} does not exist yet)",
            "",
            "The user will describe the task, often by voice (expect transcription errors), possibly mentioning",
            f"a ticket id like PROJ-313 and the repos to work in.{pending} Then, in this order:",
            "",
            f"1. Name the workstream: `wm set {key} --name \"<3-word summary>\"` and, if the user mentioned a",
            "   ticket, add `--ticket <ID>`. Lowercase, max 3 words, e.g. \"dark mode toggle\".",
            f"2. Write `{TASK_FILE}` in this folder using the format below.",
            f"3. Attach every repo: `wm add-repo {key} <repo>` (add `--branch <name>` only if the user asked to",
            "   continue an existing branch). Repo names are fuzzy-matched; if the command lists candidates,",
            "   pick the right one or ask. The command creates the worktree and branch — never do it yourself.",
            "   If the user wants to continue work already in progress in a repo's normal checkout (a branch",
            f"   and/or uncommitted changes in ~/code/<repo>), use `wm add-repo {key} <repo> --adopt` instead: it",
            "   prints a plan (stash, free the branch, move it into the worktree); show it to the user and, once",
            "   they agree, rerun it with `--yes`.",
            "4. Summarise back: name, ticket, goal, repos + branches, done-when, open questions.",
            "5. **Wait for the user to confirm before changing any code.**",
            "",
            f"Available repos: {', '.join(available_repos) or '(none found)'}",
            "",
            f"{TASK_FILE} format:",
            "",
            "```markdown",
            fmt,
            "```",
            "",
        ]

    out += ["## Repos", ""]
    if repos:
        out += ["| Folder | Repo | Branch | Base | Original checkout (read-only) |", "|---|---|---|---|---|"]
        for r in repos:
            folder = Path(r.worktree_path).name + "/"
            out.append(f"| {folder} | {r.repo} | {r.branch} | {r.base} | {r.repo_path} |")
    else:
        out.append("(none attached yet)")
    ident = ws.ticket or key
    out += [
        "",
        "## Rules",
        "",
        f"- Only modify files inside the repo subfolders above and {TASK_FILE} (plus your memory folder and your",
        "  scratchpad). The original checkouts are read-only reference.",
        "- Never create, remove or move git worktrees, and never switch branches in these worktrees.",
        "  Guard hooks enforce this; if a command is blocked, read the reason and adjust.",
        "  To look at another branch use `git show <branch>:<path>` or `git diff <branch>`.",
        f"- Need another repo? Run `wm add-repo {key} <repo>` (add `--adopt` to bring in work in progress from",
        "  its normal checkout). Never clone or cd elsewhere.",
        "- Run git commands from inside the repo subfolder (e.g. `cd acme-web && git status`).",
        f"- Commit in each repo separately; mention {ident} in commit messages.",
        f"- Open PRs with `gh pr create` from inside the worktree when asked; include {ident} in the title.",
        f"- Append to \"Decisions & progress\" in {TASK_FILE} at meaningful milestones.",
        "",
        "## Memory",
        "",
        f"Your memory folder, {memory_dir}, is shared by every workstream:",
        "what you save there shows up in all of them. Save there only what applies to any task: how the user",
        "likes to work, feedback on your behaviour, useful references.",
        f"- Facts about this task (decisions, findings, state) go in {TASK_FILE} under \"Decisions & progress\".",
        "- Facts about one repo (commands, conventions, gotchas) belong in that repo's CLAUDE.md in its worktree;",
        "  it gets committed, so propose the change to the user first.",
        "- Don't save \"project\"-type memories about this workstream: every other workstream would load them.",
        "",
        "## Done means",
        "",
        f"- Every \"Done when\" item in {TASK_FILE} is checked.",
        "- Everything is committed and pushed in every repo; report any repo left dirty or unpushed.",
        "- Don't clean up worktrees or branches — the user archives the workstream with `wm`.",
        "",
    ]
    return "\n".join(out)


HOOK_EVENTS = {
    "SessionStart": None,
    "UserPromptSubmit": None,
    "PreToolUse": "*",
    "PostToolUse": "*",
    "Notification": None,
    "Stop": None,
    "SessionEnd": None,
}


def allowed_tools(ws: Workstream, memory_dir: Path) -> list[str]:
    """Pre-approved tools, passed with --allowedTools rather than written to settings.json: project-level
    allow rules make Claude Code re-ask for folder trust on every new workstream folder."""
    return [f"Bash(wm set {ws.key} *)", f"Bash(wm add-repo {ws.key} *)", f"Edit(./{TASK_FILE})",
            f"Edit(//{str(memory_dir).strip('/')}/**)"]


def settings_json(ws: Workstream, wm: str, code_roots: list[str]) -> str:
    hooks: dict[str, list] = {}
    for event, matcher in HOOK_EVENTS.items():
        entry: dict = {"hooks": [{"type": "command", "command": f"{shlex.quote(wm)} hook {event}"}]}
        if matcher:
            entry["matcher"] = matcher
        hooks[event] = [entry]
    deny = ["EnterWorktree", "Agent(isolation:worktree)"]
    # "//" = absolute path in permission rules
    deny += [f"Edit(//{root.strip('/')}/**)" for root in code_roots]
    settings = {
        "permissions": {
            "deny": deny,
        },
        "hooks": hooks,
    }
    return json.dumps(settings, indent=2) + "\n"


def write(ws: Workstream, repos: list[RepoLink], available_repos: list[str], wm: str,
          code_roots: list[str], memory_dir: Path, pending_repos: list[str] | None = None) -> None:
    (ws.path / "CLAUDE.md").write_text(claude_md(ws, repos, available_repos, memory_dir, pending_repos))
    (ws.path / ".claude").mkdir(exist_ok=True)
    (ws.path / ".claude" / "settings.json").write_text(settings_json(ws, wm, code_roots))
